name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Windows installer (Electron)
        run: npm run dist -- --publish never

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xtream-viewer-windows
          path: dist/*.exe

      - name: Show dist folder (debug)
        if: always()
        run: |
          dir dist

      - name: Create GitHub Release and upload installer
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
